spring.application.name=BetaBooks

spring.datasource.url=jdbc:postgresql://localhost:5432/beta_books
spring.datasource.username=postgres
spring.datasource.password=100720
spring.datasource.driver-class-name=org.postgresql.Driver

# Gestione automatica dello schema
spring.jpa.hibernate.ddl-auto=update

# Genera fisicamente il file SQL con lo schema delle tabelle
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/define.sql

# Mostra le query SQL nella console di IntelliJ/Eclipse
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Specifica a Hibernate che stiamo usando le funzioni specifiche di Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect